# https://help.github.com/ja/actions/reference/workflow-syntax-for-github-actions
# You need to add some secret parameters
# - SSH_PRIVATE_KEY
# - SLACK_WEBHOOK
# - SLACK_CHANNEL_ID
name: Check PR
on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "cmd/**"
      - "internal/**"
      - "pkg/**"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: "code: check out code"
        uses: actions/checkout@v2
      - name: "parameters: set parameters"
        id: parameters
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "::set-output name=pr_number::${PR_NUMBER}"
          echo "::set-output name=go_directory::/go/src/github.com/y-miyazaki/go-layout"
          echo "::set-output name=scripts::./scripts/*.sh"
      - name: "go: test"
        run: |
          echo $SSH_PRIVATE_KEY >> ./id_rsa
          chmod +x scripts/*
          docker pull ymiyazakixyz/golang-test:latest
          docker run --rm -v $PWD:${{ steps.parameters.outputs.pr_number }} -v $PWD/id_rsa:/root/.ssh/id_rsa -w ${{ steps.parameters.outputs.pr_number }} --name golang-test ymiyazakixyz/golang-test:latest ./scripts/go-test.sh
          rm ./id_rsa
      - name: "go: upload coverage"
        uses: actions/upload-artifact@master
        with:
          name: coverage
          path: coverage
      - name: "go: golangci-lint for lint"
        uses: reviewdog/action-golangci-lint@v1
        with:
          golangci_lint_flags: "--config golangci.yaml"
          level: error
          fail_on_error: true
      - name: "shell: shellcheck for lint"
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review # Change reporter.
          path: "${{ steps.parameters.outputs.scripts }}" # Optional.
          pattern: "*" # Optional.
          exclude: "./scripts/files/*" # Optional.
          fail_on_error: true
          shellcheck_flags: -e SC2002,SC2126,SC2028,SC2140,SC2044"
      - name: "slack: notification for failed build."
        if: failure()
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_COLOR: "danger"
          SLACK_ICON: ""
          SLACK_TITLE: Failed check
          SLACK_MESSAGE: |
            This Github Actions workflow failed check.

            Pull Request
            https://github.com/${{github.repository}}/pull/${{ steps.parameters.outputs.pr_number }}
          SLACK_USERNAME: y-miyazaki
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
