# https://help.github.com/ja/actions/reference/workflow-syntax-for-github-actions
# You need to add some secret parameters
# - SSH_PRIVATE_KEY
# - SLACK_WEBHOOK
# - SLACK_CHANNEL_ID
name: Check
on:
  push:
    branches:
      - feature/**
      - develop
      - release/**
      - hotfix/**
      - master
    paths:
      - ".github/workflows/**"
      - "cmd/**"
      - "internal/**"
      - "pkg/**"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: "code: check out code"
        uses: actions/checkout@v2
      - name: "setup"
        run: |
          echo $SSH_PRIVATE_KEY >> ./id_rsa
          chmod +x scripts/*
      - name: "go: docker pull ymiyazakixyz/golang-test"
        run: |
          docker pull ymiyazakixyz/golang-test:latest
      - name: "go: test"
        run: |
          docker run --rm -v $PWD:/go/src/github.com/y-miyazaki/go-layout -v $PWD/id_rsa:/root/.ssh/id_rsa -w /go/src/github.com/y-miyazaki/go-layout --name golang-test ymiyazakixyz/golang-test:latest ./scripts/go-test.sh
      - name: "go: upload coverage"
        uses: actions/upload-artifact@master
        with:
          name: coverage
          path: coverage
      - name: "go: golangci-lint for lint"
        run: |
          docker run --rm -v $PWD:/go/src/github.com/y-miyazaki/go-layout -w /go/src/github.com/y-miyazaki/go-layout --name golang-test ymiyazakixyz/golang-test:latest golangci-lint run --tests=false --issues-exit-code 1 -c golangci.yaml ./...
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC2002,SC2126,SC2140
      - name: "slack: notification for failed build."
        if: failure()
        uses: rtCamp/action-slack-notify@v2.0.2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_COLOR: "danger"
          SLACK_ICON: ""
          SLACK_TITLE: Failed check
          SLACK_MESSAGE: |
            This Github Actions workflow failed check.
          SLACK_USERNAME: y-miyazaki
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
